### ISSUE TITLE
Base 26 not as expected

### ISSUE THREAD

**Issue by stockholmux** [aseemk/bases.js#6]
I was expecting base 26 to behave like spreadsheet column names

```
> require('bases').toBase(25,26)
'z'
> require('bases').toBase(26,26)
'ba'
```

I would have expected `require('bases').toBase(26,26)` to return `aa` rather than `ba` - is this the intended behavior? If not, is it possible to column name counting with this module?
Thanks!

**Comment by aseemk** [comment]
Hey @stockholmux, interesting q!

(For clarity to anyone else reading this, spreadsheet column names go `A`, `B`, ..., `Y`, `Z`, `AA`, `AB`, ..., `AZ`, `BA`, `BB`, etc.)

That's pretty tricky, because that's not a regular "base" alphabet compared to most others. Specifically, there's no notion of zero.

(A zero digit can be added to the left of any string, and the value will remain the same.)

Off the top of my head, perhaps one way you could achieve that is to actually use a base-27 alphabet that adds a zero, e.g. `0ABC...XYZ`, and then in your application, filter out any numbers that are multiples of 27 (0, 27, 54, etc.). The result would be spreadsheet column names.

To make the filtering easier, you could apply a transformation function, so that you can still work with regular numbers. So e.g. if you consider your columns zero-indexed (like an array), you want:

```
(numerical index) ==> (base-27 input)
0 ==> 1
1 ==> 2
2 ==> 3
...
25 ==> 26
26 ==> 28 (note this change)
27 ==> 29
...
51 ==> 53
52 ==> 55 (note this change)
53 ==> 56
...
```

I'm too braindead at this moment to translate this into a formula, but should be simple. =D

Hope that helps!

**Comment by aseemk** [comment]
Code for completeness:

``` js
var bases = require('bases');
var BASE_27 = '0ABC...XYZ';  // fill out the ...

function getColumnName(i) {
    // i is the regular zero-indexed column index, e.g. 0, 1, ... 25, 26, 27, ...
    var j = ... // transform i to exclude 0, 27, 54, ...
    return bases.toAlphabet(j, BASE_27);
}
```

**Comment by aseemk** [comment]
Okay, here's the transformation function too! =P

``` javascript
function transform(i) {
    var mult = Math.floor(i / 26);
    return i + mult + 1;
}
```

Cheers.

**Comment by stockholmux** [comment]
Nice! Yeah - the column names conversion was something that I thought would be cake at first - but it is a bit of a headache. Thanks for your work on this!
